// PLACEHOLDER — replace with the real file generated by:
//   flutterfire configure
//
// This placeholder lets the project compile before Firebase is configured.
// It intentionally throws if used so you cannot ship un-configured Firebase.
//
// After running `flutterfire configure`, this file will be overwritten with
// your real project keys. Do NOT commit real production keys to a public repo.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase is not configured for web. Run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _placeholder('android');
      case TargetPlatform.iOS:
        return _placeholder('ios');
      default:
        throw UnsupportedError(
          'Firebase not configured for $defaultTargetPlatform. '
          'Run `flutterfire configure`.',
        );
    }
  }

  /// A clearly-invalid placeholder. Replaced by `flutterfire configure`.
  static FirebaseOptions _placeholder(String platform) {
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}
